export const HOME = '/';
export const APPARELCOLLECTION = '/collections/anime-clothing-apparel';
export const APPARELTSHIRTCOLLECTION = '/collections/anime-tee-shirts';
export const APPARELTSHIRTCOLLECTIONPRODUCT ='/collections/anime-tee-shirts/products/:id';
export const APPARELHOODIECOLLECTION = '/collections/anime-hoodies-and-sweatshirts';
export const APPARELHOODIECOLLECTIONPRODUCT = '/collections/anime-hoodies-and-sweatshirts/products/:id';
export const APPARELSOCKSCOLLECTION = '/collections/anime-socks';
export const APPARELSOCKSCOLLECTIONPRODUCT = '/collections/anime-socks/products/:id';
export const APPARELCOSPLAYCOLLECTION = '/collections/anime-weeb-cosplay-accessories';
export const APPARELCOSPLAYCOLLECTIONPRODUCT = '/collections/anime-weeb-cosplay-accessories/products/:id';
export const HOMEGOODSCOLLECTION = '/collections/anime-homegoods';
export const HOMEGOODSLIGHTSCOLLECTION = '/collections/3d-led-anime-bedroom-lights-lamps';
export const HOMEGOODSLIGHTSCOLLECTIONPRODUCT = '/collections/3d-led-anime-bedroom-lights-lamps/products/:id';
export const HOMEGOODSPILLOWSCOLLECTION = '/collections/anime-kawaii-cartoon-bedroom-pillows';
export const HOMEGOODSPILLOWSCOLLECTIONPRODUCT = '/collections/anime-kawaii-cartoon-bedroom-pillows/products/:id';
export const LIFESTYLEVAPORWAVECOLLECTION = '/collections/vaporwave-aesthetic-clothing-tees-hoodies-merch';
export const LIFESTYLEVAPORWAVECOLLECTIONPRODUCT = '/collections/vaporwave-aesthetic-clothing-tees-hoodies-merch/products/:id';
export const LIFESTYLESADAESTHETICCOLLECTION = '/collections/sad-aesthetic';   //start here down
export const LIFESTYLESADAESTHETICCOLLECTIONPRODUCT = '/collections/sad-aesthetic/products/:id';
export const LIFESTYLENSFWCOLLECTION = '/collections/nsfw-anime-merch';
export const LIFESTYLENSFWCOLLECTIONPRODUCT = '/collections/nsfw-anime-merch/products/:id';
export const LIFESTYLEWAIFUCOLLECTION = '/collections/japanese-waifu-shirts-and-hoodies';
export const LIFESTYLEWAIFUCOLLECTIONPRODUCT = '/collections/japanese-waifu-shirts-and-hoodies/products/:id';
export const LIFESTYLECOSPLAYCOLLECTION = '/collections/anime-cosplay-accessories';
export const LIFESTYLECOSPLAYCOLLECTIONPRODUCT = '/collections/anime-cosplay-accessories/products/:id';
export const LIFESTYLEKAWAIICOLLECTION = '/collections/kawaii-livestyle-accessories';
export const LIFESTYLEKAWAIICOLLECTIONPRODUCT = '/collections/kawaii-livestyle-accessories/products/:id';
export const LIFESTYLESENPAICOLLECTION = '/collections/japanese-senpai-shirts-and-hoodies';
export const LIFESTYLESENPAICOLLECTIONPRODUCT = '/collections/japanese-senpai-shirts-and-hoodies/products/:id';


